# Generated by Django 5.2.17 on 2026-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
